version: "3"

tasks:
  default:
    deps:
      - validate_lint
      - run_tests


  validate_lint:
    cmds:
      - poetry run black --check --preview --diff .
      - poetry run flake8 .
      - poetry run isort -c --df .

  run_tests:
    cmds:
      - poetry run pytest --cov=real_estate_tools --cov-report term-missing --cov-fail-under=100 ./tests/
