version: "3"

tasks:
  default:
    deps:
      - validate_lint
      - run_tests


  validate_lint:
    cmds:
      - poetry run black --check --preview --diff .
      - poetry run flake8 .
      - poetry run isort -c --df .
    sources:
      - real_estate_tools/**/*.py
      - tests/**/*.py

  run_tests:
    cmds:
      - poetry run pytest --cov=real_estate_tools --cov-report term-missing --cov-fail-under=$RET_COV_THRESHOLD ./tests/
    sources:
      - real_estate_tools/**/*.py
    env:
      RET_COV_THRESHOLD: 100
